// Auto-generated by generate-types.ts — do not edit manually.
// Run: deno task generate:email-types

export type TemplateVariables = {
  "delete-account": {
    ACCOUNT_DELETION_URL: string;
    USER_NAME: string;
  };
  "email-change": {
    EMAIL_CHANGE_URL: string;
    NEW_EMAIL: string;
    USER_NAME: string;
  };
  "reset-password": {
    RESET_PASSWORD_URL: string;
    USER_NAME: string;
  };
  "sign-up-attempt": {
    SIGN_IN_URL: string;
    USER_NAME: string;
  };
  "verify-email": {
    OTP: string;
  };
};

export type TemplateName = keyof TemplateVariables;
