/**
 * Reads all HTML templates in ./templates/ and generates
 * a TypeScript type map from template names to their {{{VAR}}} placeholders.
 *
 * Usage: deno task generate:email-types
 */

const templatesDir = new URL("./templates/", import.meta.url);
const outputFile = new URL("./generated-types.ts", import.meta.url);

const variablePattern = /\{\{\{(\w+)\}\}\}/g;

const templateVars = new Map<string, Set<string>>();

for (const entry of Deno.readDirSync(templatesDir)) {
  if (!entry.isFile || !entry.name.endsWith(".html")) continue;

  const baseName = entry.name.replace(/-(?:fi|en)\.html$/, "");
  const html = Deno.readTextFileSync(new URL(entry.name, templatesDir));

  if (!templateVars.has(baseName)) {
    templateVars.set(baseName, new Set());
  }

  // deno-lint-ignore no-non-null-assertion
  const vars = templateVars.get(baseName)!;
  for (const match of html.matchAll(variablePattern)) {
    vars.add(match[1]);
  }
}

const sorted = [...templateVars.entries()].sort(([a], [b]) =>
  a.localeCompare(b)
);

const typeEntries = sorted.map(([name, vars]) => {
  const templateKey = name.replace(/\.html$/, "");
  const fields = [...vars]
    .sort()
    .map((v) => `    ${v}: string;`)
    .join("\n");
  return `  "${templateKey}": {\n${fields}\n  };`;
});

const output = `\
// Auto-generated by generate-types.ts — do not edit manually.
// Run: deno task generate:email-types

export type TemplateVariables = {
${typeEntries.join("\n")}
};

export type TemplateName = keyof TemplateVariables;
`;

Deno.writeTextFileSync(outputFile, output);

// deno-lint-ignore no-console
console.log(
  `Generated types for ${templateVars.size} templates → src/api/emails/generated-types.ts`,
);
